<h3 align="center"><strong>Cadastramento - Etapa 1 de 3</strong></h3>
<form method="POST" action ="cadastro_etapa2.php">
	<fieldset>
		<div align="center">
			<div>
				<p><b>Nome:</b><br>  
					<input type="text" name="nome" size="20">
				</p>
			</div>
			  
			<div>
				<p><b>E-mail:</b><br>  
					<input type="text" name="email" size="20">
				</p>
			</div>
			 
			<div>
				<p><b>Data de nascimento:</b><br>  
					<input type="text" name="datanascimento" size="20">
				</p>
			</div>
			
			<div>
				<p><b>Sexo:</b><br>  
					<input type="radio" value="m"checked name="sexo">Masculino&nbsp;&nbsp; 
				<input type="radio" name="sexo" value="f">Feminino</p>
			</div>
			 
			<div>
				<p><b>Profissao:</b><br>  
					<input type="text" name="profissao" size="20">
				</p>
			</div>
			  
			<div>
				<p>
					<input type="submit"value="Prosseguir &gt;&gt;" name="prosseguir">
				</p>
			</div>
		</div>
	</fieldset>
</form>
